CREATE TABLE IF NOT EXISTS mainmenu(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reserv(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    room INTEGER NOT NULL,
    people INTEGER NOT NULL,
    days INTEGER NOT NULL,
    date_reserv TEXT NOT NULL,
    time INTEGER NOT NULL
);